language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - rustup component add rustfmt-preview --toolchain nightly
  - cargo +nightly fmt --all -- --check
