language: rust
os: linux
cache: cargo

stages:
  - name: "Test"
  - name: "Style"
  - name: "Deploy"
    if: branch = master

services:
  - docker

jobs:
  fast_finish: true
  allow_failures:
    - rust: nightly
  include:
    # Disable stable & beta test till Rocket works there.
    # - name: "Stable tests"
    #   stage: "Test"
    #   rust: stable
    # - name: "Beta tests"
    #   stage: "Test"
    #   rust: beta
    - name: "Nightly tests"
      stage: "Test"
      rust: nightly
    - name: "Rust fmt"
      stage: "Style"
      rust: stable
      script:
        - rustup component add rustfmt
        - cargo fmt --all -- --check
    - name: "Docker"
      stage: "Deploy"
      # Change to stable once Rocket works
      rust: nightly
      script: ./docker-publish.sh
