version: "3.7"

services:
  backend:
    image: aethercloud/aether:latest
    build:
      context: .
      cache_from:
        - aethercloud/aether:latest
    expose:
      - 80
    networks:
      - internal

  frontend:
    image: aethercloud/frontend:latest
    build:
      context: ./frontend
      cache_from:
        - aethercloud/frontend:latest
    ports:
      - "8080:80"
    networks:
      - default
      - internal

networks:
  default:
  internal:
