{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    title: {{ .Release.Name }}-ingress
    app.kubernetes.io/name: aether
    app.kubernetes.io/release: {{ .Values.release }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: ingress
    app.kubernetes.io/managed-by: helm
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
  - http:
      paths:
      - path: /health
        backend:
          serviceName: {{ .Release.Name }}-health-service
          servicePort: 80
{{- end }}
