{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-frontend
          servicePort: 80
      - path: /api/health
        backend:
          serviceName: {{ .Release.Name }}-health
          servicePort: 80
      - path: /api/user
        backend:
          serviceName: {{ .Release.Name }}-user
          servicePort: 80
{{- end }}
