apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-health
  labels:
    app: {{ .Release.Name }}-health
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Release.Name }}-health
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-health
    spec:
      containers:
        - name: {{ .Release.Name }}-health
          image: aethercloud/health:{{ .Values.release }}
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-health
spec:
  selector:
    app: {{ .Release.Name }}-health
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
